parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Interfaces\EntityServiceInterface:
            calls:
                - [setEntityManager, ['@doctrine.orm.entity_manager']]

    App\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\Listener\DoctrineListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 1 }
            - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
